DefaultContentLanguage = "sv"
baseurl = "http://www.hemmlis.se/"
cloudinary_url = "https://res.cloudinary.com/hemmlis/image/upload/"
publishDir = "docs"
theme = "hemmlis"
[Languages.en]
languageName = "English"
title = "Hemmlis"
[[Languages.en.menu.main]]
identifier = "how"
name = "How does it work?"
url = "/how/"
weight = 3
[[Languages.en.menu.main]]
identifier = "lease"
name = "Lease furniture"
url = "/lease/"
weight = 2
[[Languages.en.menu.main]]
identifier = "jobs"
name = "Jobs"
url = "/jobs/"
weight = 4
[[Languages.en.menu.main]]
identifier = "collections"
name = "Collections"
url = "/collections/"
weight = 1
[[Languages.en.menu.main]]
identifier = "about"
name = "About us"
url = "/about/"
weight = 5
[[Languages.en.menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 6
[Languages.sv]
languageName = "Svenska"
title = "Hemmlis"
[[Languages.sv.menu.main]]
identifier = "how"
name = "Hur fungerar det?"
url = "/how/"
weight = 3
[[Languages.sv.menu.main]]
identifier = "lease"
name = "Hyr möbler"
url = "/lease/"
weight = 2
[[Languages.sv.menu.main]]
identifier = "jobs"
name = "Jobb"
url = "/jobs/"
weight = 4
[[Languages.sv.menu.main]]
identifier = "collections"
name = "Våra kollektioner"
url = "/collections/"
weight = 1
[[Languages.sv.menu.main]]
identifier = "about"
name = "Om oss"
url = "/about/"
weight = 5
[[Languages.sv.menu.main]]
identifier = "partners"
name = "Samarbetspartners"
url = "/partners/"
weight = 6
[[Languages.sv.menu.main]]
identifier = "contact"
name = "Kontakt"
url = "/contact/"
weight = 7
